### ISSUE TITLE
add a good README 

### ISSUE THREAD

**Issue by NanheSingh** [NanheSingh/guess-the-number#1]

**Comment by Den1f** [comment]
Can you assign this issue to me?

**Comment by NanheSingh** [comment]
> Can you assign this issue to me?
yeah sure

**Comment by vaanyasharmaaa** [comment]
@NanheSingh Can you assign this issue to me?

**Comment by Den1f** [comment]
@vaanyasharmaaa hey, are you interested in working some other project? I have something in my mind and also I found your LinkedIn profile interesting so. If yes then let me know at 
https://www.linkedin.com/in/deep-808bb3241

**Comment by NanheSingh** [comment]
@vaanyasharmaaa thank you for your contribution.
